# Generated by Django 5.1.7 on 2025-04-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_user_delete_role_delete_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_amount', models.IntegerField(max_length=100)),
                ('dish_price', models.CharField(max_length=100)),
            ],
        ),
    ]
