# Generated by Django 5.1.7 on 2025-04-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_dishtable_dish_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishtable',
            name='dish_amount',
            field=models.IntegerField(),
        ),
    ]
