# Generated by Django 5.1.7 on 2025-04-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_dishtable_dish_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishtable',
            name='dish_price',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
