# Generated by Django 5.1.7 on 2025-04-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_dishtable_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishtable',
            name='dish_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
