# Generated by Django 5.1.7 on 2025-04-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_dishtable_dish_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False, verbose_name='供应商唯一标识（自增主键）')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='供应商名称（唯一约束）')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='主要联系人姓名')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系电话')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系邮箱')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='详细地址')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
