# Generated by Django 5.1.7 on 2025-04-11 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False, verbose_name='库存记录唯一标识')),
                ('product_name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('expiration_data', models.CharField(blank=True, max_length=255, null=True, verbose_name='保质期限')),
                ('warehouse_loc', models.CharField(blank=True, max_length=255, null=True, verbose_name='仓库位置')),
                ('batch_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='批次号')),
                ('category', models.CharField(blank=True, choices=[('生鲜', '生鲜'), ('冻品', '冻品'), ('调料', '调料')], max_length=10, null=True, verbose_name='分类标签')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='app01.dishtable', verbose_name='FK_inventory')),
            ],
        ),
    ]
