# Generated by Django 5.1.7 on 2025-04-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='分类标签'),
        ),
    ]
