# Generated by Django 5.1.7 on 2025-04-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_alter_inventory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='库内商品名称'),
        ),
    ]
