# Generated by Django 5.1.7 on 2025-04-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_alter_inventory_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='库内商品数量'),
            preserve_default=False,
        ),
    ]
