# Generated by Django 5.1.7 on 2025-04-22 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_inventory_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionRecord',
            fields=[
                ('idconsumption_record', models.AutoField(primary_key=True, serialize=False)),
                ('consumption_name', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.CharField(max_length=45)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='App01SupplierHasApp01Inventory',
            fields=[
                ('app01_supplier_supplier', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app01.supplier')),
                ('app01_inventory_inventory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app01.inventory')),
            ],
        ),
    ]
