# Generated by Django 5.1.7 on 2025-04-22 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_consumptionrecord_app01supplierhasapp01inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App01SupplierHasApp01Inventory',
            new_name='SupplierHasApp01Inventory',
        ),
    ]
