# Generated by Django 5.1.7 on 2025-04-22 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_rename_app01supplierhasapp01inventory_supplierhasapp01inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierHasApp01Inventory',
            new_name='SupplierHasInventory',
        ),
    ]
