# Generated by Django 5.1.7 on 2025-04-22 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_rename_supplierhasapp01inventory_supplierhasinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=80, null=True)),
                ('gender', models.CharField(max_length=45)),
                ('age', models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameField(
            model_name='consumptionrecord',
            old_name='idconsumption_record',
            new_name='consumption_id',
        ),
        migrations.AddField(
            model_name='consumptionrecord',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumptionRecord2', to='app01.dishtable', verbose_name='FK_consumptionRecord2'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='consumption_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='consumptionrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumptionRecord', to='app01.customer', verbose_name='FK_consumptionRecord1'),
        ),
    ]
