# Generated by Django 5.1.7 on 2025-05-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
    ]
