# Generated by Django 5.1.7 on 2025-05-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_alter_customer_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishtable',
            name='dish_name',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
    ]
