# Generated by Django 5.1.7 on 2025-05-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_alter_dishtable_dish_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishtable',
            name='dish_price',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
